#!/usr/bin/env python3
"""Build compact C-derived assembly and independent expected memory/I/O results.

No arguments are required by the auto tester. Edit the configuration below to
generate a different reproducible case. This script never invokes an RTL tool.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import random
import re
import subprocess
import sys
import tempfile


TEST_ROOT = Path(__file__).resolve().parent
AUTO_TESTER_ROOT = TEST_ROOT.parents[2]
WORKSPACE_ROOT = TEST_ROOT.parents[3]
COMPILER_PATH = WORKSPACE_ROOT / "compiler" / "vscc"
ASM_TO_MEM_PATH = AUTO_TESTER_ROOT / "verification" / "scripts" / "asmtomem.py"
SOURCE_DIR = TEST_ROOT / "src"
SOURCE_GENERATED_DIR = SOURCE_DIR / "generated"
OUTPUT_DIR = TEST_ROOT / "generated"

# Editable generation settings. RANDOM_SEED=None selects and reports a new seed.
A0_SEED = 0x1A2B3C4D
RX_NAME = "VSCPU3x"
RANDOM_SEED: int | None = 0x3C0DE
PATTERN_LENGTH_MIN = 8
PATTERN_LENGTH_MAX = 8
GPIO_INITIAL_SEED = 0x02AA

CORE_CAPACITIES = {"a0": 1536, "cm": 2048, "ct": 2560}
CORE_SOURCES = {"a0": "agent_0.c", "cm": "codemaker.c", "ct": "control_tower.c"}
MASK32 = 0xFFFFFFFF


class GenerationError(RuntimeError):
    """The case cannot be built safely with the selected configuration/tools."""


def polynomial(value: int) -> int:
    return (1664525 * value + 1013904223) & MASK32


def memory_result(seed: int, count: int) -> int:
    """Oracle only: the two RAM inversions restore the polynomial input."""
    if count < 1:
        raise GenerationError("a memory sweep must contain at least one word")
    for _ in range(count):
        seed = polynomial(seed)
    return seed ^ MASK32


def gpio_results(inputs: list[int]) -> list[int]:
    state = GPIO_INITIAL_SEED
    result = []
    for value in inputs:
        state = polynomial(value ^ state) & 0x3FF
        result.append(state)
    return result


def _validate_case(seed: int, rx_name: str, gpio_inputs: list[int]) -> bytes:
    if type(seed) is not int or not 0 <= seed <= MASK32:
        raise GenerationError("A0 seed must be a 32-bit unsigned integer")
    if not isinstance(rx_name, str):
        raise GenerationError("RX_NAME must be an ASCII string")
    try:
        name = rx_name.encode("ascii")
    except UnicodeEncodeError as exc:
        raise GenerationError("RX_NAME must be an ASCII string") from exc
    if b"\0" in name or len(name) > 250:
        raise GenerationError("RX_NAME must contain no NUL and at most 250 bytes")
    if type(GPIO_INITIAL_SEED) is not int or not 0 <= GPIO_INITIAL_SEED <= 0x3FF:
        raise GenerationError("GPIO_INITIAL_SEED must be a 10-bit unsigned integer")
    if not 1 <= len(gpio_inputs) <= 127 or any(
        type(value) is not int or not 0 <= value <= 0x3FF for value in gpio_inputs
    ):
        raise GenerationError("GPIO pattern must contain 1..127 ten-bit samples")
    return name


def choose_gpio_inputs() -> tuple[list[int], int]:
    if (
        type(PATTERN_LENGTH_MIN) is not int
        or type(PATTERN_LENGTH_MAX) is not int
        or not 1 <= PATTERN_LENGTH_MIN <= PATTERN_LENGTH_MAX <= 127
    ):
        raise GenerationError("pattern bounds must satisfy 1 <= min <= max <= 127")
    if RANDOM_SEED is not None and type(RANDOM_SEED) is not int:
        raise GenerationError("RANDOM_SEED must be an integer or None")
    rng_seed = RANDOM_SEED
    if rng_seed is None:
        rng_seed = random.SystemRandom().getrandbits(64)
    rng = random.Random(rng_seed)
    count = rng.randint(PATTERN_LENGTH_MIN, PATTERN_LENGTH_MAX)
    return [rng.randrange(1024) for _ in range(count)], rng_seed


def _run(command: list[str], *, source: str | None = None) -> str:
    result = subprocess.run(
        command, input=source, capture_output=True, text=True, check=False,
        cwd=TEST_ROOT, timeout=60,
    )
    if result.returncode or "Skipping " in result.stdout:
        raise GenerationError(
            f"{Path(command[0]).name} failed or skipped input:\n"
            + result.stdout + result.stderr
        )
    return result.stdout


def _header(core: str, base: int, seed: int, gpio_count: int) -> str:
    header = (
        "/* Generated by ../../generate.py; addresses and sizes are WORDS. */\n"
        f"#define ARRAY_BASE {base}\n"
        f"#define CORE_WORDS {CORE_CAPACITIES[core]}\n"
    )
    if core == "a0":
        header += f"#define A0_SEED 0x{seed:08X}u\n"
    if core == "ct":
        header += (
            f"#define GPIO_INITIAL_SEED {GPIO_INITIAL_SEED}u\n"
            f"#define GPIO_SAMPLE_COUNT {gpio_count}u\n"
        )
    return header


def _compiler_source(core: str, header: str) -> str:
    source = (SOURCE_DIR / CORE_SOURCES[core]).read_text(encoding="ascii")
    source = source.replace(f'#include "generated/memory_chain_{core}_params.h"', header)
    source = source.replace('#include "common.h"', (SOURCE_DIR / "common.h").read_text())
    # vscc currently has no volatile qualifier syntax. Its loads/stores are
    # retained; execution regressions check the actual emitted access sequence.
    source = re.sub(r"\bvolatile\s+", "", source)
    return "/* Flattened for vscc; volatile qualifiers removed by generate.py. */\n" + source


def assembly_layout(assembly: str) -> dict:
    addresses = []
    mnemonics: dict[str, int] = {}
    for raw in assembly.splitlines():
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        match = re.fullmatch(r"(\d+):\s+(.+)", line)
        if not match:
            raise GenerationError(f"unrecognized assembly: {raw}")
        addresses.append(int(match[1]))
        fields = match[2].split()
        if fields[0].isdigit():
            if len(fields) != 1 or not 0 <= int(fields[0]) <= MASK32:
                raise GenerationError(f"invalid data word: {raw}")
        else:
            if len(fields) != 3 or any(not field.isdigit() for field in fields[1:]):
                raise GenerationError(f"invalid instruction: {raw}")
            if any(not 0 <= int(field) < 16384 for field in fields[1:]):
                raise GenerationError(f"instruction operand exceeds 14 bits: {raw}")
            mnemonics[fields[0]] = mnemonics.get(fields[0], 0) + 1
    if not addresses or sorted(addresses) != list(range(len(addresses))):
        raise GenerationError("compiler image must be contiguous from word zero")
    if "//$STACK_SECTION // none" not in assembly:
        raise GenerationError("tail allocation requires the stackless calling convention")
    return {"program_words": len(addresses), "text_words": sum(mnemonics.values()),
            "mnemonics": dict(sorted(mnemonics.items()))}


def read_memory(path: Path) -> list[int]:
    words = []
    address = 0
    for raw in path.read_text(encoding="ascii").splitlines():
        for token in raw.split("//", 1)[0].split():
            if token.startswith("@"):
                address = int(token[1:], 16)
            else:
                value = int(token, 16)
                if address != len(words) or not 0 <= value <= MASK32:
                    raise GenerationError(f"noncontiguous or invalid memory image: {path}")
                words.append(value)
                address += 1
    return words


def compile_core(core: str, source_dir: Path, output_dir: Path, seed: int,
                 gpio_count: int) -> dict:
    # No large C array is declared: a pointer reserves all words after the
    # compiled image. Recompile until the immediate pointer matches that end.
    base = CORE_CAPACITIES[core] - 1
    for _ in range(8):
        header = _header(core, base, seed, gpio_count)
        source = _compiler_source(core, header)
        assembly = _run([str(COMPILER_PATH)], source=source)
        layout = assembly_layout(assembly)
        end = layout["program_words"]
        if not 0 < end < CORE_CAPACITIES[core]:
            raise GenerationError(f"{core} image leaves no array: {end} words")
        if end == base:
            break
        base = end
    else:
        raise GenerationError(f"{core} array base did not stabilize")

    asm_path = source_dir / f"memory_chain_{core}.asm"
    asm_path.write_text(
        f"// Array: [{base}, {CORE_CAPACITIES[core]}) words; intentionally absent from image.\n"
        + assembly, encoding="ascii",
    )
    (source_dir / f"memory_chain_{core}.generated.c").write_text(source, encoding="ascii")
    (source_dir / f"memory_chain_{core}_params.h").write_text(header, encoding="ascii")
    _run([sys.executable, str(ASM_TO_MEM_PATH), str(asm_path)])
    mem_path = asm_path.with_suffix(".mem")
    if len(read_memory(mem_path)) != end:
        raise GenerationError(f"converter changed {core} image length")
    mem_path.replace(output_dir / mem_path.name)
    return {**layout, "array_base": base, "array_words": CORE_CAPACITIES[core] - base,
            "memory_words": CORE_CAPACITIES[core]}


def _write_memory(path: Path, values: list[int]) -> None:
    path.write_text("@0\n" + "".join(f"{word:08X}\n" for word in values), encoding="ascii")


def generate_case(output_dir: Path, *, source_dir: Path | None = None,
                  seed: int = A0_SEED, rx_name: str = RX_NAME,
                  gpio_inputs: list[int] | None = None) -> dict:
    rng_seed = None
    if gpio_inputs is None:
        gpio_inputs, rng_seed = choose_gpio_inputs()
    name = _validate_case(seed, rx_name, gpio_inputs)
    for tool in (COMPILER_PATH, ASM_TO_MEM_PATH):
        if not tool.is_file():
            raise GenerationError(f"required tool is missing: {tool}")
    output_dir = Path(output_dir)
    if source_dir is None:
        source_dir = output_dir.parent / "src" / "generated"
    source_dir = Path(source_dir)
    output_dir.parent.mkdir(parents=True, exist_ok=True)
    metadata = {"seed": seed, "rx_name": rx_name, "random_seed": rng_seed,
                "gpio_initial_seed": GPIO_INITIAL_SEED, "gpio_inputs": gpio_inputs,
                "gpio_expected": gpio_results(gpio_inputs), "cores": {},
                "compiler_sha256": hashlib.sha256(COMPILER_PATH.read_bytes()).hexdigest()}

    with tempfile.TemporaryDirectory(prefix=".memory-chain-", dir=output_dir.parent) as tmp:
        staging = Path(tmp)
        staged_source, staged_output = staging / "source", staging / "output"
        staged_source.mkdir()
        staged_output.mkdir()
        state = seed
        expected = []
        for core in ("a0", "cm", "ct"):
            layout = compile_core(core, staged_source, staged_output, seed, len(gpio_inputs))
            state = memory_result(state, layout["array_words"])
            layout["expected"] = state
            metadata["cores"][core] = layout
            expected.append(state)
        _write_memory(staged_output / "memory_chain_shd.mem", [0] * 4)
        _write_memory(staged_output / "memory_chain_shd_chk.mem", expected)
        _write_memory(staged_output / "memory_chain_gpio_in.mem", gpio_inputs)
        _write_memory(staged_output / "memory_chain_gpio_out_chk.mem", metadata["gpio_expected"])
        (staged_output / "memory_chain_uart_tx_buf.txt").write_bytes(name + b"\0")
        (staged_output / "memory_chain_uart_rx_buf.txt").write_bytes(b"Hello " + name)
        (staged_source / "manifest.json").write_text(
            json.dumps(metadata, indent=2) + "\n", encoding="ascii",
        )
        # Publish only after all three builds, layouts and conversion checks pass.
        output_dir.mkdir(parents=True, exist_ok=True)
        source_dir.mkdir(parents=True, exist_ok=True)
        for path in staged_source.iterdir():
            path.replace(source_dir / path.name)
        for path in staged_output.iterdir():
            path.replace(output_dir / path.name)
    return metadata


def main() -> int:
    try:
        metadata = generate_case(OUTPUT_DIR, source_dir=SOURCE_GENERATED_DIR,
                                 seed=A0_SEED, rx_name=RX_NAME)
    except (GenerationError, OSError, ValueError, subprocess.SubprocessError) as exc:
        print(f"memory_chain generation failed: {exc}", file=sys.stderr)
        return 1
    print(f"Generated memory_chain: A0 seed=0x{A0_SEED:08X}, RX_NAME={RX_NAME!r}, "
          f"GPIO samples={len(metadata['gpio_inputs'])}, RNG seed={metadata['random_seed']}")
    for core, layout in metadata["cores"].items():
        print(f"  {core}: load {layout['program_words']} words; "
              f"sweep [{layout['array_base']}, {layout['memory_words']}) "
              f"({layout['array_words']} words); result=0x{layout['expected']:08X}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
