#!/usr/bin/env python3
"""Generate a randomized GPIO chained-XOR test case.

This script intentionally takes no command-line arguments.  Edit the settings
below when a different generation policy or local tool path is needed.
"""

from __future__ import annotations

from pathlib import Path
import random
import subprocess
import sys


# ---------------------------------------------------------------------------
# Editable generation settings
# ---------------------------------------------------------------------------

# A length is selected inclusively from this range for every generation run.
# Set both values equal to produce a fixed-length pattern.  Hardware supports
# lengths from 1 through 127 samples.
PATTERN_LENGTH_MIN = 1
PATTERN_LENGTH_MAX = 127

# None gives each invocation a fresh seed.  Set an integer to reproduce a case.
RANDOM_SEED: int | None = None

# Preserve the initial value used by the original gpio_xor test.  Input samples
# and the selected pattern length are randomized; each output is chained back
# as the XOR value used for the following sample.
INITIAL_XOR_VALUE = 0x02AA


TEST_DIR = Path(__file__).resolve().parent
AUTO_TESTER_ROOT = TEST_DIR.parents[2]
WORKSPACE_ROOT = TEST_DIR.parents[3]

# These paths may be replaced with absolute paths for another local checkout.
COMPILER_PATH = WORKSPACE_ROOT / "compiler" / "vscc"
ASMTOMEM_PATH = AUTO_TESTER_ROOT / "verification" / "scripts" / "asmtomem.py"


SOURCE_PATH = TEST_DIR / "src" / "gpio_xor_cm.c"
SOURCE_GENERATED_DIR = TEST_DIR / "src" / "generated"
RUNNER_GENERATED_DIR = TEST_DIR / "generated"

HEADER_NAME = "gpio_xor_params.h"
HEADER_PATH = SOURCE_GENERATED_DIR / HEADER_NAME
COMPILER_SOURCE_PATH = SOURCE_GENERATED_DIR / "gpio_xor_cm.generated.c"
ASSEMBLY_PATH = SOURCE_GENERATED_DIR / "gpio_xor_cm.asm"
INTERMEDIATE_PROGRAM_MEM_PATH = ASSEMBLY_PATH.with_suffix(".mem")

PROGRAM_MEM_PATH = RUNNER_GENERATED_DIR / "gpio_xor_cm.mem"
GPIO_INPUT_MEM_PATH = RUNNER_GENERATED_DIR / "gpio_xor_gpio_in.mem"
GPIO_OUTPUT_CHECK_MEM_PATH = (
    RUNNER_GENERATED_DIR / "gpio_xor_gpio_out_chk.mem"
)

DATA_MASK = 0x03FF
INCLUDE_DIRECTIVE = '#include "generated/gpio_xor_params.h"'


def _validate_configuration() -> None:
    if not isinstance(PATTERN_LENGTH_MIN, int) or not isinstance(
        PATTERN_LENGTH_MAX, int
    ):
        raise ValueError("pattern-length bounds must be integers")
    if not 1 <= PATTERN_LENGTH_MIN <= PATTERN_LENGTH_MAX <= 127:
        raise ValueError(
            "pattern-length bounds must satisfy "
            "1 <= PATTERN_LENGTH_MIN <= PATTERN_LENGTH_MAX <= 127"
        )
    if not isinstance(INITIAL_XOR_VALUE, int) or not (
        0 <= INITIAL_XOR_VALUE <= DATA_MASK
    ):
        raise ValueError("INITIAL_XOR_VALUE must be a 10-bit integer")
    if RANDOM_SEED is not None and not isinstance(RANDOM_SEED, int):
        raise ValueError("RANDOM_SEED must be an integer or None")
    if not SOURCE_PATH.is_file():
        raise FileNotFoundError(f"GPIO source file not found: {SOURCE_PATH}")
    if not COMPILER_PATH.is_file():
        raise FileNotFoundError(f"VSCPU compiler not found: {COMPILER_PATH}")
    if not ASMTOMEM_PATH.is_file():
        raise FileNotFoundError(f"asmtomem script not found: {ASMTOMEM_PATH}")


def _effective_seed() -> int:
    if RANDOM_SEED is not None:
        return RANDOM_SEED
    return random.SystemRandom().randrange(1 << 64)


def _chained_xor(inputs: list[int]) -> list[int]:
    value = INITIAL_XOR_VALUE
    outputs: list[int] = []
    for input_value in inputs:
        value = (input_value ^ value) & DATA_MASK
        outputs.append(value)
    return outputs


def _render_header(pattern_length: int, rng_seed: int) -> str:
    return (
        "/* Generated by ../../generate.py; edit that script, not this file. */\n"
        f"/* Reproduce this pattern with RANDOM_SEED = {rng_seed}. */\n"
        f"#define GPIO_INITIAL_SEED 0x{INITIAL_XOR_VALUE:04X}\n"
        f"#define GPIO_SAMPLE_COUNT {pattern_length}\n"
    )


def _render_compiler_source(source: str, header: str) -> str:
    include_count = source.count(INCLUDE_DIRECTIVE)
    if include_count != 1:
        raise RuntimeError(
            f"expected exactly one {INCLUDE_DIRECTIVE!r} in {SOURCE_PATH}, "
            f"found {include_count}"
        )

    flattened_header = (
        "/* Begin generated/gpio_xor_params.h. */\n"
        f"{header.rstrip()}\n"
        "/* End generated/gpio_xor_params.h. */"
    )
    return source.replace(INCLUDE_DIRECTIVE, flattened_header)


def _render_pattern_mem(description: str, values: list[int], rng_seed: int) -> str:
    words = "\n".join(f"{value:03X}" for value in values)
    return (
        f"// {description}\n"
        f"// Reproduce with RANDOM_SEED = {rng_seed}.\n"
        "@0\n"
        f"{words}\n"
    )


def _run_tool(command: list[str], description: str) -> subprocess.CompletedProcess[str]:
    try:
        completed = subprocess.run(
            command,
            check=False,
            cwd=TEST_DIR,
            text=True,
            capture_output=True,
        )
    except OSError as exc:
        raise RuntimeError(f"could not run {description}: {exc}") from exc
    if completed.returncode != 0:
        details = "\n".join(
            part.strip()
            for part in (completed.stdout, completed.stderr)
            if part.strip()
        )
        suffix = f":\n{details}" if details else ""
        raise RuntimeError(
            f"{description} failed with exit status {completed.returncode}{suffix}"
        )
    if description == "asmtomem converter" and "Skipping " in completed.stdout:
        raise RuntimeError(
            "asmtomem skipped compiler output:\n" + completed.stdout.strip()
        )
    return completed


def main() -> None:
    _validate_configuration()
    SOURCE_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    RUNNER_GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    rng_seed = _effective_seed()
    rng = random.Random(rng_seed)
    pattern_length = rng.randint(PATTERN_LENGTH_MIN, PATTERN_LENGTH_MAX)
    inputs = [rng.randrange(DATA_MASK + 1) for _ in range(pattern_length)]
    expected_outputs = _chained_xor(inputs)

    header = _render_header(pattern_length, rng_seed)
    source = SOURCE_PATH.read_text(encoding="utf-8")
    compiler_source = _render_compiler_source(source, header)

    HEADER_PATH.write_text(header, encoding="utf-8")
    COMPILER_SOURCE_PATH.write_text(compiler_source, encoding="utf-8")

    _run_tool(
        [str(COMPILER_PATH), str(COMPILER_SOURCE_PATH), "-o", str(ASSEMBLY_PATH)],
        "VSCPU compiler",
    )
    _run_tool(
        [sys.executable, str(ASMTOMEM_PATH), str(ASSEMBLY_PATH)],
        "asmtomem converter",
    )
    if not INTERMEDIATE_PROGRAM_MEM_PATH.is_file():
        raise RuntimeError(
            "asmtomem completed without producing "
            f"{INTERMEDIATE_PROGRAM_MEM_PATH}"
        )

    INTERMEDIATE_PROGRAM_MEM_PATH.replace(PROGRAM_MEM_PATH)
    GPIO_INPUT_MEM_PATH.write_text(
        _render_pattern_mem(
            "Random 10-bit GPI[9:0] samples; GPI[10] is owned by test_driver.",
            inputs,
            rng_seed,
        ),
        encoding="utf-8",
    )
    GPIO_OUTPUT_CHECK_MEM_PATH.write_text(
        _render_pattern_mem(
            "Chained XOR results; GPO[10] is ignored by the checker.",
            expected_outputs,
            rng_seed,
        ),
        encoding="utf-8",
    )

    print(
        f"Generated gpio_xor: {pattern_length} samples, RNG seed {rng_seed}\n"
        f"Runner inputs: {RUNNER_GENERATED_DIR}"
    )


if __name__ == "__main__":
    main()
